api_platform:
    resource: .
    type: api_platform
    prefix: /api
api_excel_upload:
    path: '/api/excel/upload'
    controller: App\Controller\ExcelUploadController::upload
    methods: ['POST']
